stages:
  - test
  - build
  - publish

tests:
  stage: test
  image: rust
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --assume-yes protobuf-compiler libprotobuf-dev
    - cargo install sqlx-cli
    - export "DATABASE_URL=sqlite:///tmp/udplbd.db"
    - sqlx database setup
    - cargo test

build:amd64:
  stage: build
  image: rust
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --assume-yes protobuf-compiler libprotobuf-dev
    - cargo install sqlx-cli
    - export "DATABASE_URL=sqlite:///tmp/udplbd.db"
    - sqlx database setup    - cargo build --release
  artifacts:
    paths:
      - target/release/udplbd

rustdoc:
  stage: build
  image: rust
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --assume-yes protobuf-compiler libprotobuf-dev
    - cargo install sqlx-cli
    - export "DATABASE_URL=sqlite:///tmp/udplbd.db"
    - sqlx database setup    - cargo doc
  artifacts:
    paths:
      - target/doc

pages:
  stage: publish
  image: alpine
  dependencies:
    - build:amd64
    - rustdoc
  script:
    - mkdir -p public
    - mv target/doc public/doc
    - mv target/release/udplbd public/udplbd-amd64
  artifacts:
    paths:
      - public
  only:
    - master
