image: docker

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  DOCKER_TLS_CERT_DIR: ""
  RELEASE_BRANCH: "main"
  DEV_BRANCH: "develop"
  MAIN_BRANCH: "main"
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA

stages:
  - build
  - test
  - push
  - deploy
  - doctor

include:
  - project: "security/container-scanning"
    file: ".ESnet-container-scan.yml"
  - component: $CI_SERVER_FQDN/ht/cicd-common/aap-run@v0.3.0
    inputs:
      aap_token: $AAP_TOKEN

.wharf_logout: &wharf_logout |-
  docker logout "$WHARF_SITE"

.wharf_login: &wharf_login |-
  echo "$WHARF_TOKEN" | docker login -u "$WHARF_USER" "$WHARF_SITE" --password-stdin

.docker_login: &docker_login |-
  echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

.build_environment:
  image: rust:latest
  before_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install
      --no-install-recommends --assume-yes protobuf-compiler libprotobuf-dev
      sqlite3 libssl-dev musl-tools
    - rustup target add x86_64-unknown-linux-musl
    - cargo install sqlx-cli cargo-audit
    - export "DATABASE_URL=sqlite:///tmp/udplbd.db"
    - echo "Setting up database"
    - $CARGO_HOME/bin/sqlx database setup

build_udplbd:
  stage: build
  extends: .build_environment
  script:
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/udplbd
    expire_in: 3 month

build_docs:
  stage: build
  extends: .build_environment
  script:
    - cargo doc --no-deps
    - mv target/doc public
  artifacts:
    paths:
      - public

build_container:
  stage: build
  script:
    - *docker_login
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

test:unit:
  extends: .build_environment
  stage: test
  script:
    - cargo test --release --lib

test:mock_integration:
  extends: .build_environment
  stage: test
  script:
    - cargo test --release --bin udplbd -- --nocapture

test:audit:
  extends: .build_environment
  stage: test
  script:
    - cargo audit
  allow_failure: true

.push:
  stage: push
  before_script:
    - *docker_login
    - *wharf_login
  after_script:
    - *wharf_logout
  script:
    - |
      docker pull $IMAGE_TAG
      for tag in $TAGS; do
        if echo $tag | grep -q "BRANCH_TAG"; then
          tag=$(echo $tag | sed "s/BRANCH_TAG/$(echo $CI_COMMIT_BRANCH | sed 's/\//-/g')/g")
        fi
        docker tag $IMAGE_TAG $tag
        docker push $tag
      done;

publish_container:
  extends: .push
  variables:
    TAGS: |
      $WHARF_SITE/$WHARF_PROJECT/$CI_PROJECT_NAME:$CI_PIPELINE_ID
      $WHARF_SITE/$WHARF_PROJECT/$CI_PROJECT_NAME:BRANCH_TAG

publish_release_container:
  extends: .push
  rules:
    - if: "$CI_COMMIT_BRANCH == $MAIN_BRANCH"
    - if: $CI_COMMIT_TAG
  variables:
    TAGS: |
      $WHARF_SITE/$WHARF_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
      $WHARF_SITE/$WHARF_PROJECT/$CI_PROJECT_NAME:latest

deploy_alpha:
  extends: .aap_run
  stage: deploy
  variables:
    AAP_JOB_TEMPLATE: 747
    AAP_LIMIT: node2.fpga.es.net
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

deploy_node4_cicd9:
  extends: .aap_run
  stage: deploy
  variables:
    AAP_JOB_TEMPLATE: 882
    AAP_LIMIT: node4.fpga.es.net
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

doctor_node4_cicd9:
  extends: .aap_run
  stage: doctor
  variables:
    AAP_JOB_TEMPLATE: 883
    AAP_LIMIT: node4.fpga.es.net
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  after_script:
    - |
      xml_str=$(printf "$(printf "$(grep 'doctor\.stdout' stdout.txt | cut -d: -f2)\n")\n")
      printf "${xml_str:2:${#xml_str}-3}\n" > doctor.xml
  artifacts:
    reports:
      junit: output/doctor.xml
