[package]
name = "udplbd"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "udplbd"
path = "src/main.rs"

[lib]
name = "udplbd"
path = "src/lib.rs"

[dependencies]
async-stream = "0.3.6"
axum = { version = "0.8.3", features = ["macros"] }
axum-extra = { version = "0.10.1", features = ["form", "query"] }
byteorder = "1.5.0"
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.35", features = ["derive", "env"] }
futures = "0.3.31"
futures-util = "0.3.31"
hex = "0.4"
hyper = "1.6.0"
hyper-util = "0.1.11"
ipnetwork = { version = "0.21.1", features = ["serde"] }
lazy_static = "1.5.0"
log = "0.4.27"
macaddr = { version = "1.0", features = ["serde"] }
prometheus = "0.14.0"
prost = "0.13.3"
prost-types = "0.13.3"
prost-wkt = "0.6.0"
prost-wkt-types = "0.6.0"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
serde_yaml = "0.9.34"
sha2 = "0.10"
sqlx = { version = "0.8.3", features = [
    "sqlite",
    "runtime-tokio-native-tls",
    "chrono",
] }
tempfile = "3.16.0"
thiserror = "2.0.12"
tokio = { version = "1.43.0", features = ["full"] }
tokio-stream = "0.1.17"
tokio-util = "0.7.13"
tonic = { version = "0.13.0", features = [
    "transport",
    "gzip",
    "tls-webpki-roots",
    "tls-native-roots",
] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
turmoil = "0.6.5"
url = { version = "2.5.4", features = ["serde"] }
uuid = { version = "1.13.1", features = ["v4"] }
zerocopy = { version = "0.8.24", features = ["zerocopy-derive"] }
zerocopy-derive = "0.8.24"


[target.'cfg(target_os = "linux")'.dependencies]
rtnetlink = "0.16.0"
netlink-packet-route = "0.22.0"
net-route = "0.4.5"

[build-dependencies]
prost-wkt-build = "0.6.0"
tonic-build = "0.13.0"

[profile.release]
incremental = true
lto = "thin"
